## Problem Statement
#### To build a simple logistic regression model for prediction of demand of bikes given the values about the wind speed.

In [42]:
import numpy as np
import pandas as pd
from glob import glob
import matplotlib.pyplot as plt

In [25]:
data = pd.read_csv('Bike-Sharing-Dataset/day.csv')
data.head(5)

,instant,dteday,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0,1,2011-01-01,1,0,1,0,6,0,2,0.344167,0.363625,0.805833,0.160446,331,654,985
1,2,2011-01-02,1,0,1,0,0,0,2,0.363478,0.353739,0.696087,0.248539,131,670,801
2,3,2011-01-03,1,0,1,0,1,1,1,0.196364,0.189405,0.437273,0.248309,120,1229,1349
3,4,2011-01-04,1,0,1,0,2,1,1,0.200000,0.212122,0.590435,0.160296,108,1454,1562
4,5,2011-01-05,1,0,1,0,3,1,1,0.226957,0.229270,0.436957,0.186900,82,1518,1600

In [26]:
data_list = glob('Bike-Sharing-Dataset/*')
day_df = pd.read_csv(data_list[2])
day_df.head()

,instant,dteday,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0,1,2011-01-01,1,0,1,0,6,0,2,0.344167,0.363625,0.805833,0.160446,331,654,985
1,2,2011-01-02,1,0,1,0,0,0,2,0.363478,0.353739,0.696087,0.248539,131,670,801
2,3,2011-01-03,1,0,1,0,1,1,1,0.196364,0.189405,0.437273,0.248309,120,1229,1349
3,4,2011-01-04,1,0,1,0,2,1,1,0.200000,0.212122,0.590435,0.160296,108,1454,1562
4,5,2011-01-05,1,0,1,0,3,1,1,0.226957,0.229270,0.436957,0.186900,82,1518,1600

In [51]:
X = data[['windspeed']]
y = data['High_Demand'] = data.cnt.map(lambda x:1 if x> 4600 else 0)

In [52]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=101)

In [53]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()
classifier.fit(X_train,y_train)

LogisticRegression()

In [54]:
y_pred = classifier.predict(X_test)
pd.DataFrame({'y Test': y_test, 'y Pred': y_pred})

     y Test  y Pred
479       1       0
648       1       0
139       1       1
601       1       1
116       0       0
..      ...     ...
492       1       0
212       0       0
438       1       1
83        0       0
176       1       1

[220 rows x 2 columns]

In [55]:
from sklearn.metrics import accuracy_score, confusion_matrix
cm = confusion_matrix(y_test,y_pred)
print(cm)
accuracy_score(y_test,y_pred)

[[99 11]
 [84 26]]

0.5681818181818182